parameters:
#    your_books_user.example.class: YourBooks\UserBundle\Example

#services:
#    your_books_user.example:
#        class: %your_books_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    your_books.registration.form.type:
        class: YourBooks\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: yourbooks_user_registration }
    yourbooks.user.user_registration_listener:
            class: YourBooks\UserBundle\ConfirmMail\UserRegistrationListener
            arguments: [@mailer]
            tags:
                - { name: kernel.event_listener, event: userbundle.confirmmail.user_register, method: onUserRegister }