parameters:
#    your_books_user.example.class: YourBooks\UserBundle\Example

services:
#    your_books_user.example:
#        class: %your_books_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
