<?php

namespace YourBooks\BookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookStatusRepository extends EntityRepository
{
}
