<?php

namespace YourBooks\BookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookCategoryRepository extends EntityRepository
{
}
