your_books_paypal:
    resource: "@YourBooksPaypalBundle/Resources/config/routing.yml"
    prefix:   /

your_books_main:
    resource: "@YourBooksMainBundle/Resources/config/routing.yml"
    prefix:   /

your_books_book:
    resource: "@YourBooksBookBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

your_books_user:
    resource: "@YourBooksUserBundle/Resources/config/routing.yml"
    prefix:   /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin