your_books_main_author_homepage:
    pattern:  /
    defaults: { _controller: YourBooksMainBundle:Author:index }

your_books_main_author_send_book:
    pattern:  /send_book
    defaults: { _controller: YourBooksMainBundle:Author:send }

your_books_main_author_parameters:
    pattern:  /parameters
    defaults: { _controller: YourBooksMainBundle:Author:parameters }

your_books_main_author_profile:
    pattern:  /profile
    defaults: { _controller: YourBooksMainBundle:Author:profile }

your_books_main_author_edit_profile:
    pattern:  /profile/edit
    defaults: { _controller: YourBooksMainBundle:Author:editProfile }
    methods: [get]

your_books_main_author_update_profile:
    pattern:  /profile/update/
    defaults: { _controller: YourBooksMainBundle:Author:updateProfile }
    methods: [post, put]

your_books_main_author_inscription:
    pattern:  /inscription
    defaults: { _controller: YourBooksMainBundle:Author:inscription }

your_books_main_author_retracted_book:
    pattern:  /retracted/{id}
    defaults: { _controller: YourBooksMainBundle:Author:retractedBook }
    requirements:
        id: \d+