your_books_main_editor_homepage:
    pattern:  /{category}
    defaults: { _controller: YourBooksMainBundle:Editor:index, category: null }
    requirements:
        category: \d+

your_books_main_editor_historic:
    pattern:  /historic
    defaults: { _controller: YourBooksMainBundle:Editor:historic }

your_books_main_editor_profile_author:
    pattern:  /show/author/{id}
    defaults: { _controller: YourBooksMainBundle:Editor:showAuthorProfile }
    requirements:
            id: \d+

your_books_main_editor_parameters:
    pattern:  /parameters
    defaults: { _controller: YourBooksMainBundle:Editor:parameters }

your_books_main_editor_profile:
    pattern:  /profile
    defaults: { _controller: YourBooksMainBundle:Editor:profile }

your_books_main_editor_download:
    pattern:  /download/{id}
    defaults: { _controller: YourBooksMainBundle:Editor:download }
    requirements:
        id: \d+
your_books_main_search_book:
  pattern: /book/recherche
  defaults: { _controller: YourBooksMainBundle:Editor:searchBook }
  requirements:
    _method: POST
your_books_main_search_book_cat:
  pattern: /book/recherche/cat
  defaults: { _controller: YourBooksMainBundle:Editor:searchBookCat }
  requirements:
    _method: POST
your_books_main_order_book:
  pattern: /book/order
  defaults: { _controller: YourBooksMainBundle:Editor:orderBook }
  requirements:
    _method: POST
your_books_main_order_book_cat:
  pattern: /book/recherche/cat
  defaults: { _controller: YourBooksMainBundle:Editor:orderBookCat }
  requirements:
    _method: POST
your_books_main_category_search_book:
  pattern: /book/category
  defaults: { _controller: YourBooksMainBundle:Editor:searchCategoryBook }
  requirements:
    _method: POST
your_books_main_auto_completion_search:
  pattern: /book/autocompletion
  defaults: { _controller: YourBooksMainBundle:Editor:autoCompletion }
  requirements:
    _method: POST
your_books_main_auto_completion_search_cat:
  pattern: /book/autocompletion/cat
  defaults: { _controller: YourBooksMainBundle:Editor:autoCompletionCat }
  requirements:
    _method: POST