your_books_main_editor_homepage:
    pattern:  /{category}
    defaults: { _controller: YourBooksMainBundle:Editor:index, category: null }
    requirements:
        category: \d+

your_books_main_editor_historic:
    pattern:  /historic
    defaults: { _controller: YourBooksMainBundle:Editor:historic }

your_books_main_editor_profile_author:
    pattern:  /show/author/{id}
    defaults: { _controller: YourBooksMainBundle:Editor:showAuthorProfile }
    requirements:
            id: \d+

your_books_main_editor_parameters:
    pattern:  /parameters
    defaults: { _controller: YourBooksMainBundle:Editor:parameters }

your_books_main_editor_profile:
    pattern:  /profile
    defaults: { _controller: YourBooksMainBundle:Editor:profile }

your_books_main_editor_download:
    pattern:  /download/{id}
    defaults: { _controller: YourBooksMainBundle:Editor:download }
    requirements:
        id: \d+