your_books_main_reader_homepage:
    pattern:  /
    defaults: { _controller: YourBooksMainBundle:Reader:index }

your_books_main_reader_inscription:
    pattern:  /inscription
    defaults: { _controller: YourBooksMainBundle:Reader:inscription }

your_books_main_reader_parameters:
    pattern:  /parameters
    defaults: { _controller: YourBooksMainBundle:Reader:parameters }

your_books_main_reader_profile:
    pattern:  /profile
    defaults: { _controller: YourBooksMainBundle:Reader:profile }

your_books_review_upload:
    pattern:  /review/{id}
    defaults: { _controller: YourBooksMainBundle:Reader:review }
    requirements:
        id: \d+

your_books_main_received:
    pattern:  /received/{id}
    defaults: { _controller: YourBooksMainBundle:Reader:received }
    requirements:
        id: \d+

your_books_reader_registration_register:
    pattern:  /{account}
    defaults: { _controller: YourBooksUserBundle:Registration:register }
    requirements: { _method: GET }