parameters:
#    your_books_paypal.example.class: YourBooks\PaypalBundle\Example

services:
#    your_books_paypal.example:
#        class: %your_books_paypal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
