services:
    sonata.admin.footer:
        class: YourBooks\MainBundle\Admin\FooterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Footer", label: "Footer" }
        arguments:
            - ~
            - YourBooks\MainBundle\Entity\Footer
            - ~