your_books_main_author:
    resource: "@YourBooksMainBundle/Resources/config/routing/author.yml"
    prefix:   /author

your_books_main_editor:
    resource: "@YourBooksMainBundle/Resources/config/routing/editor.yml"
    prefix:   /editor

your_books_main_reader:
    resource: "@YourBooksMainBundle/Resources/config/routing/reader.yml"
    prefix:   /reader

your_books_main_download_book:
    pattern:  /download/book/{id}
    defaults: { _controller: YourBooksMainBundle:Main:downloadBook }
    requirements:
        id: \d+

your_books_main_homepage:
    pattern:  /
    defaults: { _controller: YourBooksMainBundle:Main:index }

your_books_main_contact:
    pattern:  /contact
    defaults: { _controller: YourBooksMainBundle:Main:contact }

your_books_main_engagements:
    pattern:  /engagements
    defaults: { _controller: YourBooksMainBundle:Main:engagements }

your_books_main_presse:
    pattern:  /presse
    defaults: { _controller: YourBooksMainBundle:Main:presse }

your_books_main_download_presse:
    pattern:  /download/presse/{id}
    defaults: { _controller: YourBooksMainBundle:Main:downloadPresse }
    requirements:
        id: \d+

your_books_main_conditions:
    pattern:  /conditions
    defaults: { _controller: YourBooksMainBundle:Main:conditions }

your_books_main_partenaires:
    pattern:  /partenaires
    defaults: { _controller: YourBooksMainBundle:Main:partenaires }

your_books_main_mentionslegales:
    pattern:  /legal
    defaults: { _controller: YourBooksMainBundle:Main:mentionslegales }

your_books_main_outils:
    pattern:  /outils
    defaults: { _controller: YourBooksMainBundle:Main:outils }