your_books_main_author:
    resource: "@YourBooksMainBundle/Resources/config/routing/author.yml"
    prefix:   /author

your_books_main_editor:
    resource: "@YourBooksMainBundle/Resources/config/routing/editor.yml"
    prefix:   /editor

your_books_main_reader:
    resource: "@YourBooksMainBundle/Resources/config/routing/reader.yml"
    prefix:   /reader

your_books_main_homepage:
    pattern:  /
    defaults: { _controller: YourBooksMainBundle:Main:index }
