parameters:
#    your_books_main.example.class: YourBooks\MainBundle\Example

services:
#    your_books_main.example:
#        class: %your_books_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
