parameters:
#    your_books_main.example.class: YourBooks\MainBundle\Example

services:
    yourbooks.main.mail_event_listener:
        class: YourBooks\MainBundle\ConfirmMail\MailEventListener
        arguments: [@mailer]
        tags:
            - { name: kernel.event_listener, event: mainbundle.confirmmail.mail_event, method: onMailEvent }
    yourbooks.main.delayDaysOut:
        class: YourBooks\MainBundle\Twig\DelayDaysExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
    yourbooks.main.delayDateOut:
            class: YourBooks\MainBundle\Twig\DelayDateExtension
            arguments: ["@service_container"]
            tags:
                - { name: twig.extension }
