your_books_user_security_login:
    pattern:  /login
    defaults: { _controller: YourBooksUserBundle:Security:login }

your_books_user_security_check:
    pattern:  /login_check
    defaults: { _controller: YourBooksUserBundle:Security:check }

your_books_user_security_logout:
    pattern:  /logout
    defaults: { _controller: YourBooksUserBundle:Security:logout }