your_books_user_profile_show:
    pattern:  /
    defaults: { _controller: YourBooksUserBundle:Profile:show }
    requirements: { _method: GET }

your_books_user_profile_edit:
    pattern:  /edit
    defaults: { _controller: YourBooksUserBundle:Profile:edit }
