services:
    sonata.admin.book:
        class: YourBooks\BookBundle\Admin\BookAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Book", label: "Book" }
        arguments:
            - ~
            - YourBooks\BookBundle\Entity\Book
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]