services:
    sonata.admin.book:
        class: YourBooks\BookBundle\Admin\BookAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Book", label: "Book" }
        arguments:
            - ~
            - YourBooks\BookBundle\Entity\Book
            - ~
    sonata.admin.book_category:
        class: YourBooks\BookBundle\Admin\BookCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Book", label: "Category" }
        arguments:
            - ~
            - YourBooks\BookBundle\Entity\BookCategory
            - ~