services:
    sonata.admin.book:
        class: YourBooks\BookBundle\Admin\BookAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Book", label: "Book" }
        arguments:
            - ~
            - YourBooks\BookBundle\Entity\Book
            - ~
    sonata.admin.book_category:
        class: YourBooks\BookBundle\Admin\BookCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Book", label: "Category" }
        arguments:
            - ~
            - YourBooks\BookBundle\Entity\BookCategory
            - ~
    sonata.admin.book_family_category:
            class: YourBooks\BookBundle\Admin\BookFamilyCategoryAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Book", label: "FamilyCategory" }
            arguments:
                - ~
                - YourBooks\BookBundle\Entity\BookFamilyCategory
                - ~
    sonata.admin.book_status:
        class: YourBooks\BookBundle\Admin\BookStatusAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Book", label: "Status" }
        arguments:
            - ~
            - YourBooks\BookBundle\Entity\BookStatus
            - ~
    sonata.admin.book_review:
            class: YourBooks\BookBundle\Admin\BookReviewAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Book", label: "Review" }
            arguments:
                - ~
                - YourBooks\BookBundle\Entity\BookReview
                - ~