parameters:
#    your_books_book.example.class: YourBooks\BookBundle\Example

services:
#    your_books_book.example:
#        class: %your_books_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
