parameters:
#    your_books_book.example.class: YourBooks\BookBundle\Example

services:
#    your_books_book.example:
#        class: %your_books_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    your_books_book.book.listener:
        class: YourBooks\BookBundle\Listener\BookListener
        arguments:
            - @event_dispatcher
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }