<?php

namespace YourBooks\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConditionsUtilisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionsUtilisationRepository extends EntityRepository
{

}