<?php

namespace YourBooks\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EspacePresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspacePresseRepository extends EntityRepository
{

}